
POST http://localhost:3000/api/v1/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZXhhbXBsZS5jb20iLCJzdWIiOiI2NmQ5NjdmOC1iMWFiLTQ2MDYtOTk0My05MTNjZGE5YWIyYTUiLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjU2NTIwMTksImV4cCI6MTc2NTY1MjkxOX0.ZbLnc5u4ljAVwL1HNLTs7EbFtUGfpoJdvwicPMD-XSI
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123",
  "name": "John Doe",
  "role": "STUDENT"
}

###
GET http://localhost:3000/api/v1/courses?page=5&limit=5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN0dWRlbnRAZXhhbXBsZS5jb20iLCJzdWIiOiI3NGNlNTkxYy03ZGY1LTQ5MDItYWEzZi01ZWJkYjliMDI5OTEiLCJyb2xlIjoiU1RVREVOVCIsImlhdCI6MTc2NTkwMTM0MywiZXhwIjoxNzY1OTAyMjQzfQ.fMM4PklUkDSHfzVNibevtVhzgcnBFwv-DISzji64k-M
